server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: http://localhost:8086
          predicates:
            - Path=/movies/**

        - id: catalogRoute
          uri: http://localhost:8087
          predicates:
            - Path=/catalogs/**

        - id: serieRoute
          uri: http://localhost:8088
          predicates:
            - Path=/series/**
