server:
  port: ${PORT:8090}

spring:
  application:
    name: movie-service

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    password: sa

  jpa:
    hibernate:
      ddl-auto: create-drop

  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    username: guest      

queue:
  movie:
    name: movieQueue

