server:
  port: ${PORT:8088}

spring:
  application:
    name: serie-service

  # data:
  #   mongodb:
  #     database: finalBackEnd
  #     port: '27017'

  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    username: guest      

queue:
  serie:
    name: serieQueue